id = "redis"
image = "docker.io/library/redis:4.0-alpine"

[network]
	type = "macvlan"
	name = "orbit0"
	[network.ipam]
		type = "orbit-network"

[resources]
	cpu = 1.5
	memory = 64

[services]
	[services.redis]
		port = 6379
		labels = ["dev"]
