id = "redis"
image = "docker.io/library/redis:4.0-alpine"

[network]
	type = "bridge"
	name = "boss"
	bridge = "boss0"
	[network.ipam]
		type = "host-local"
		subnet = "10.10.0.0/16"

[resources]
	cpu = 1.5
	memory = 64

[services]
	[services.redis]
		port = 6379
		labels = ["dev"]
